# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherAppSwiftUI

  target 'WeatherAppSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAppSwiftUIUITests' do
    # Pods for testing
  end

end
